### ISSUE TITLE
Estilo (linha 727 em js)

### ISSUE THREAD

**Issue by kyriosdata** [newtonjose/cs-2019-01#13]
Este estilo é mais legível que i += 1, por exemplo, amplamente empregado pelo seu código. Para sistemas de informação em geral, o estilo preferido é i = i + 1. Não é preciso fazer alteração no código já produzido, mas sugiro que mude o estilo nos próximos exercícios em benefício da legibilidade.

**Comment by newtonjose** [comment]
FIXED nos códigos java. [commit](https://github.com/newtonjose/cs-2019-01/commit/9891c59f35a6566f95cae459c2c0b1ccd5699f98])
