### ISSUE TITLE
Software Design (reunir implementações na classe Algoritmos)

### ISSUE THREAD

**Issue by kyriosdata** [newtonjose/cs-2019-01#19]
Agrupar funções na classe Algoritmos tem efeito parecido com o que já é clássico, por exemplo, basta observar a classe Math tanto em Java quanto em JavaScript. Minha sugestão é que reúna todos os métodos lá. 

Neste caso, a remoção da classe Algoritmos (#15) é suspendida.

**Comment by newtonjose** [comment]
Fiz essa modelagem para os testes ficarem organizados.
